#!/usr/bin/env dash

# main menu to access instantASSIST

ASSIST=$(cat cache/cache | instantmenu -i -p instantASSIST -F -ct | grep -o '^.')

[ -z "$ASSIST" ] && exit

if [ -d assists/"$ASSIST" ]; then
    ASSIST2="$(instantmenu -i -p instantASSIST -n -h 32 -F -ct <cache/"$ASSIST"/cache | grep -o '^.')"
    [ -z "$ASSIST2" ] && exit
    SCRIPTPATH=assists/"$ASSIST/$ASSIST2"
else
    if ! [ -e assists/"$PAPERAPP" ]; then
        echo "assist not found"
        exit
    fi
    SCRIPTPATH=assists/"$ASSIST"
fi

"${SCRIPTPATH}.sh" &
iconf lastassist "${SCRIPTPATH}.sh"

