start = [
  "notify-send 'Profile set!'",
  "notify-send 'You are now using profile ~mine~ :)'"
]

[dots]
xmonad = "mine"
xmobar = "mine"
rofi = "default"
dunst = "instantos"
nvim = "mine"
alacritty = "mine"
zellij = "mine"
picom = "mine"
