[pyprland]
plugins = [
 "expose",
 "fetch_client_menu",
 "lost_windows",
 "magnify",
 "scratchpads",
 "shift_monitors",
 "toggle_special",
 "workspaces_follow_focus",
]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
term_classed = "kitty --class"

[scratchpads.term]
command = "alacritty --class termscratchpad"
class = "termscratchpad"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

